language: rust
install:
  - curl http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz |
    sudo tar --strip-components 1 -C /usr -xzf -
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo clean
  - cargo build --verbose
env:
  - LD_LIBRARY_PATH=/usr/local/lib
